# Generated by Django 5.2.4 on 2025-08-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acta',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='actas/'),
        ),
    ]
